version: '3.8'

services:
  database:
    image: postgres:16.1-alpine3.19
    container_name: database_ttinv
    restart: always
    volumes:
      - database_volume:/var/lib/postgresql/data/    
    env_file:
      - ./.env
    # expose:
    #   - "5432"
    ports:
      - "5432:5432"
    networks:
      - network

  web:
    build: 
      context: .
    ports:
      - 8000:8000
    container_name: web_ttinv
    restart: always
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/ttinv/
      - web_static_volume:/usr/src/ttinv/static
      - web_media_volume:/usr/src/ttinv/media
    depends_on:
      - database
    env_file:
      - ./.env
    networks:
      - network

  nginx:
    build: ./nginx
    container_name: nginx_ttinv
    networks:
      - network
    ports:
      - 1337:80
    depends_on:
      - web
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - web_static_volume:/home/src/ttinv/static
      - web_media_volume:/home/src/ttinv/media 
      
volumes:
  database_volume:
  web_static_volume:
  web_media_volume:

networks:
  network:
    driver: bridge